/* import type { Metadata } from 'next'
import { Inter } from 'next/font/google' */
"use client"
import './globals.css'
import Navbar from '@/components/Navbar'
import { ThemeProvider } from "next-themes"
import Footer from '@/components/Footer'

/* const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 */
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <html lang="en">
    {
}
    <head />
    <body>
      <ThemeProvider enableSystem={true} attribute="class">
      <Navbar/>
      {children}
      <Footer />
      </ThemeProvider>
    </body>
  </html>

  )
}
